### ISSUE TITLE
notworking with phonegap

### ISSUE THREAD

**Issue by vinodhum** [flowplayer/flowplayer-mpegdash#6]
is this supported on phonegap ?

**Comment by blacktrash** [comment]
By phonegap do you mean this framework: http://phonegap.com/ ? Then this is not the place to talk about Flowplayer integration into development frameworks, at least not without more details.

Or are you talking about the playback problem on Android, like in your forum post at https://flowplayer.org/forum/#!/setup:mpeg-dash-with-flowplayer ?
Both the README and the demo mention the Android issue with AAC_HE. Does the second example on the demo page work?

As MPEG-DASH is still sort of experimental we expect problems, but again, please provide more details: which device? which OS version etc. etc.

**Comment by blacktrash** [comment]
As per forum also Android Lollipop as covered at length here: https://github.com/flowplayer/flowplayer-mpegdash/commit/1de538ea6cbeeec1be0ec448af4b976e1520a292#commitcomment-12997450

@ipernet - does the AAC_HE video still have to be there for reference in the Chromium bug report? I can't follow https://code.google.com/p/chromium/issues/detail?id=527411 because I get a 403. I could put it somewhere else, and have the AAC_LC example on our demo site.

**Comment by ipernet** [comment]
Hi @blacktrash 

The HE-AAC demo video is not required anymore as a reference., you can change it.

FYI the Chrome team has fixed the bug: 
https://chromium.googlesource.com/chromium/src.git/+/0b5ec458acf03e3507a3737cfc483df0694cf803%5E%21/ but I haven't tested it yet.

**Comment by blacktrash** [comment]
@ipernet - thanks. I understand the code that AAC_HE now should work (once one uses an OS version featuring the change), or have I got it muddled up?
If I'm right, we can leave the demo as is.

**Comment by ipernet** [comment]
@blacktrash this is correct, this should work on the next chrome release so you can leave the demo as is!

**Comment by blacktrash** [comment]
@ipernet - thanks.
Closing this.
